on: 
  push:
    branches:
      - master
name: deploy website on push
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    
    steps:
    - name: get latest code
      uses: actions/checkout@v2
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 7.2

    - name: Install Dependencies
      run: composer install

    - name: Copy ENV Laravel Configuration for CI
      run: php -r "file_exists('.env') || copy('.env.production', '.env');"
    
    - name: Generate Key
      run: php artisan key:generate

    - uses: actions/setup-node@master
    - name: Installing project dependencies
      run: npm install

    - name: Building the project
      run: npm run production

    # - name: Execute tests
    #   run: vendor/bin/phpunit

    - name: Sync Files
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: novara.id.domainesia.com
        username: ${{secrets.ftp_username}}
        password: ${{secrets.ftp_password}}
        server-dir: /studio2/
        exclude: |
          **/.git*
          **/.git*/**
          **/vendor*/**
          **/node_modules/**

    # - name: Deploy to production
    #   uses: appleboy/ssh-action@master
    #   with:
    #     username: ${{secrets.ssh_username}}
    #     password: ${{secrets.ssh_password}}
    #     host: akdevstudios.com
    #     port: 64000
    #     script: 'cd /home/akdevstu/studio1 && ./server_deploy.sh'
